server:
  port: 3344
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/One-mini-learner-yang/springcloud-config.git
          username: 2975165963@qq.com
          password: 200058yzd
          search-paths: springcloud-config
      label: master
  rabbitmq:
    host: 192.168.234.128
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    fetch-registry: true
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
